# Jekyll configuration
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
markdown: kramdown
sass:
  style: compressed

# Site settings
title: 'BuildingSyncÂ®'
title_html: 'BuildingSync<sup>&reg;</sup>'
description: 'Standardizing Energy Audit Data Collection.'
language: 'en-us'
baseurl: ''
url: 'http://schema.buildingsync.net/'
google_analytics: UA-18838154-16
